interface defaultTables{
                sqlite_sequence:table
                realname_auth:table
                session:table
                _uni_id_users_old_20230831:table
                signin_records:table
                webinfo:table
                zhaopin:table
                banner:table
                bill:table
                clientssay:table
                contact:table
                cropper:table
                files:table
                friendlink:table
                image:table
                message:table
                _news_articles_old_20241221:table
                pages:table
                tag:table
                tag_relationship:table
                _domain_old_20230805:table
                news_categories:table
                _theme_old_20240207:table
                domain:table
                uni_id_users:table
                theme:table
                news_articles:table
                }
            export = defaultTables